# Generated by Django 3.2.6 on 2021-08-12 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_teams_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='fisrt_name',
            new_name='first_name',
        ),
    ]
